apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nanoaod-argo-
spec:
  entrypoint: parallel-worker

  podGC:
    # pod gc strategy must be one of the following
    # * OnPodCompletion - delete pods immediately when pod is completed (including errors/failures)
    # * OnPodSuccess - delete pods immediately when pod is successful
    # * OnWorkflowCompletion - delete pods when workflow is completed
    # * OnWorkflowSuccess - delete pods when workflow is successful
    strategy: OnPodSuccess

  parallelism: 120

  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: nfs-1

  templates:
  - name: nanoaod-argo
    inputs:
      parameters:
      - name: files
      - name: it
    script:
      imagePullPolicy: Never
      image: cmsopendata/cmssw_5_3_32
      command: [sh]
      source: |
        source /opt/cms/entrypoint.sh
        sudo chown $USER /mnt/vol
        mkdir workspace
        cd workspace
        git clone git://github.com/cms-opendata-analyses/AOD2NanoAODOutreachTool  AOD2NanoAOD
        cd AOD2NanoAOD
        scram b -j8
        varfiles="{{inputs.parameters.files}}"
        sed -i 's,files =,#files =,g' configs/data_cfg.py
        sed -i 's,files.extend,#files.extend,g' configs/data_cfg.py
        sed -i "s,*files,'$varfiles',g" configs/data_cfg.py
        cmsRun configs/data_cfg.py
        iterator="{{inputs.parameters.it}}"
        cp output.root /mnt/vol/output$iterator.root
        echo  ls -l /mnt/vol
        ls -l /mnt/vol
      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol

  - name: parallel-worker
    dag:
      tasks:

